# 这个配置使用专门的公共库工作流
# 复制自 oscms-deployment/examples/common-library-workflow.yml

name: Build and Publish Common Library

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run tests
      run: mvn test

    - name: Build with Maven
      run: mvn clean compile

    - name: Package library
      run: mvn package -DskipTests -Dmaven.javadoc.skip=true

    - name: Publish to GitHub Packages
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      run: mvn deploy -DskipTests -Dmaven.javadoc.skip=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: oscms-common-artifacts
        path: target/*.jar
        retention-days: 30